[package]
name = "yotredash"
version = "0.2.0"
authors = ["Ash Levy <ashy.of.ren@gmail.com>"]

[dependencies]
clap = "2.29.0"
env_logger = "0.5.3"
failure = "0.1.1"
font-loader = "0.5.0"
freetype-rs = "0.16.0"
log = "0.4.1"
nfd = "0.0.4"
notify = "4.0.3"
owning_ref = "0.3.3"
rect_packer = "0.2.1"
serde = "1.0.26"
serde_derive = "1.0.26"
serde_yaml = "0.7.3"
solvent = "0.8.1"
time = "0.1.38"
winit = "0.9.0"

# Needed by opengl feature
glium = { git = "https://github.com/ashkitten/glium", optional = true }

# Needed by image feature
gif = { version = "0.9.2", optional = true }
gif-dispose = { version = "2.1.0", optional = true }
image = { version = "0.18.0", optional = true }

# Needed by audio feature
portaudio = { version = "0.7.0", optional = true }
rb = { version = "0.3.1", optional = true }
fftw = { version = "0.4.0", optional = true }
num-traits = { version = "0.2.0", optional = true }

[target.'cfg(unix)'.dependencies]
signal = "0.4.0"

[dev-dependencies]
glob = "0.2.11"

[features]
default = ["opengl", "image-src", "audio"]
opengl = ["glium"]
image-src = ["gif", "gif-dispose", "image"]
audio = ["portaudio", "rb", "fftw", "num-traits"]

[replace]
"servo-fontconfig-sys:4.0.4" = { git = "https://github.com/ashkitten/libfontconfig" }
